# Generated by Django 4.2.5 on 2023-10-10 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("graph_1", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GrowthCurve",
            new_name="File",
        ),
    ]
